### ISSUE TITLE
Version 2.0 Roadmap

### ISSUE THREAD

**Issue by bencorlett** [thephpleague/oauth1-client#34]
Thoughts for V2 development...

- [ ] Move to PSR-7 (Guzzle 6) #27 
- [ ] Consistent API with OAuth 2 client #28 
- [ ] Send arbitrary requests? #20 

/cc @stevenmaguire @shadowhand

**Comment by bencorlett** [comment]
Closing issue in favour of a PR instead.
